apiVersion: v1
kind: Service
metadata:
  name: nfs-server
  namespace: nfs-server
spec:
  selector:
    app: nfs-server
  type: LoadBalancer
  externalTrafficPolicy: Local
  ipFamilyPolicy: SingleStack
  ipFamilies:
    - IPv4
  ports:
  - name: nfs
    port: 2049
    targetPort: nfs
  #loadBalancerIP: 192.168.129.206
