kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  finalizers:
    - kubernetes.io/pvc-protection
  name: pvcfornfs
  namespace: nfs-server
  labels:
    app.kubernetes.io/name: nfs-server
    app.kubernetes.io/instance: nfs-server  
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 50Gi
